# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['src\\cli\\cli.py'],
    pathex=['.', 'src'],
    binaries=[],
    datas=[
        ('assets', 'assets'),
        ('assets/Metadata.png', '.'),
        ('src/core/risk/rules.yaml', 'src/core/risk'),
    ],
    hiddenimports=[
        # src package modules
        'src',
        'src.cli',
        'src.cli.cli',
        'src.cli.output',
        'src.cli.validation',
        'src.config',
        'src.config.logging_config',
        'src.core',
        'src.core.database',
        'src.core.database.db',
        'src.core.editor',
        'src.core.editor.editor',
        'src.core.extractor',
        'src.core.extractor.extractor',
        'src.core.reports',
        'src.core.reports.report',
        'src.core.risk',
        'src.core.risk.risk_analyzer',
        'src.core.risk.risk_engine',
        'src.core.risk.rule_models',
        'src.core.risk.yaml_parser',
        'src.core.services',
        'src.core.services.container',
        'src.core.services.analytics_service',
        'src.core.services.editor_service',
        'src.core.services.extraction_service',
        'src.core.services.history_service',
        'src.core.services.report_service',
        'src.core.services.risk_service',
        'src.models',
        'src.models.analytics',
        'src.models.metadata',
        'src.models.reports',
        'src.models.risk',
        'src.utils',
        'src.utils.logger',
        # third-party
        'rich',
        'rich.console',
        'rich.table',
        'rich.panel',
        'rich.box',
        'rich.markup',
        'rich.text',
        'typer',
        'click',
        'pandas',
        'PIL',
        'PIL.Image',
        'PIL.ExifTags',
        'PyPDF2',
        'reportlab',
        'reportlab.lib',
        'reportlab.lib.pagesizes',
        'reportlab.platypus',
        'hachoir',
        'hachoir.parser',
        'hachoir.metadata',
        'yaml',
        'piexif',
        'mutagen',
        'openpyxl',
        'docx',
        'matplotlib',
        'matplotlib.pyplot',
        'importlib.metadata',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'PyQt5',
        'PyQt6',
        'wx',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='TraceLens-cli',
    icon='assets/Metadata.ico',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
